"""Sample YAML config for tests.

What the Wire UI's Step 3 generates fake values but all real sections,
plus comments and blank lines to exercise the parser.
"""

from __future__ import annotations

# All tests use this change it here and they all see it automatically.
SAMPLE_CONFIG_YAML: str = """\
# Wire Fact Gathering Tool configuration
# Generated by UI Step 3

admin_host:
  ip: 10.0.0.1
  user: deploy
  ssh_key: ~/.ssh/id_rsa
  ssh_port: 22

cluster:
  domain: wire.example.com
  kubernetes_namespace: wire-prod

databases:
  cassandra: 10.0.1.1
  elasticsearch: 10.0.1.2
  minio: 10.0.1.3
  postgresql: 10.0.1.4

options:
  check_kubernetes: true
  check_databases: true
  check_network: false
  check_wire_services: yes
  output_format: "jsonl"
  output_file: results.jsonl # default output path

kubernetes_context: prod-cluster
timeout: 60
"""
