"""Unit tests for the YAML parser (src/lib/yaml_parser.py)."""

import unittest

from src.lib.yaml_parser import parse_yaml, get_nested


class TestYamlParser(unittest.TestCase):
    """Tests for parse_yaml and get_nested functions."""

    def test_parse_full_config(self) -> None:
        """Parse the exact YAML format generated by the UI's Step 3 wizard."""
        yaml_text = '''# Wire Fact Gathering Tool Settings File
admin_host:
  ip: "10.0.0.1"
  user: "wire-admin"
  ssh_key: "~/.ssh/wire_deploy"
  ssh_port: 22

cluster:
  domain: "wire.example.com"
  kubernetes_namespace: "wire"

databases:
  cassandra: "10.0.0.10"
  elasticsearch: "10.0.0.11"
  minio: "10.0.0.12"
  postgresql: "10.0.0.13"

options:
  check_kubernetes: true
  check_databases: true
  check_network: true
  check_wire_services: true
  output_format: "jsonl"
  output_file: "wire-facts-results.jsonl"'''

        result = parse_yaml(yaml_text)

        # Verify admin_host section
        self.assertEqual(result["admin_host"]["ip"], "10.0.0.1")
        self.assertEqual(result["admin_host"]["ssh_port"], 22)

        # Verify cluster section
        self.assertEqual(result["cluster"]["domain"], "wire.example.com")

        # Verify databases section
        self.assertEqual(result["databases"]["cassandra"], "10.0.0.10")

        # Check booleans and strings in the options section
        self.assertIs(result["options"]["check_kubernetes"], True)
        self.assertEqual(result["options"]["output_format"], "jsonl")

    def test_parse_comments_and_blank_lines(self) -> None:
        """We should skip comments and blank lines when parsing."""
        yaml_text = '''# Comment line
key1: "value1"

# Another comment
key2: 42
'''
        result = parse_yaml(yaml_text)

        # Only two keys should be parsed
        self.assertEqual(len(result), 2)
        self.assertEqual(result["key1"], "value1")
        self.assertEqual(result["key2"], 42)

    def test_parse_booleans(self) -> None:
        """Boolean values (true/false/yes/no) are parsed correctly."""
        yaml_text = '''a: true
b: false
c: yes
d: no'''
        result = parse_yaml(yaml_text)

        # Use assertIs for identity checks on True/False
        self.assertIs(result["a"], True)
        self.assertIs(result["b"], False)
        self.assertIs(result["c"], True)
        self.assertIs(result["d"], False)

    def test_parse_nested_keys(self) -> None:
        """Nested keys via indentation produce nested dictionaries."""
        yaml_text = '''parent:
  child1: "a"
  child2: "b"'''
        result = parse_yaml(yaml_text)

        self.assertIsInstance(result["parent"], dict)
        self.assertEqual(result["parent"]["child1"], "a")
        self.assertEqual(result["parent"]["child2"], "b")

    def test_get_nested(self) -> None:
        """Dotted path access and default values."""
        data = {"a": {"b": {"c": 42}}}

        # Successful deep traversal
        self.assertEqual(get_nested(data, "a.b.c"), 42)

        # Missing key returns explicit default
        self.assertEqual(get_nested(data, "a.b.d", "default"), "default")

        # Missing key with no explicit default returns None
        self.assertIsNone(get_nested(data, "x.y.z"))

        # Partial path returns sub-dict
        self.assertEqual(get_nested(data, "a"), {"b": {"c": 42}})

    def test_parse_integers_and_floats(self) -> None:
        """Numeric values are parsed as their correct Python types."""
        yaml_text = '''port: 22
ratio: 3.14
negative: -5
zero: 0'''
        result = parse_yaml(yaml_text)

        self.assertEqual(result["port"], 22)
        self.assertIsInstance(result["port"], int)

        self.assertEqual(result["ratio"], 3.14)
        self.assertIsInstance(result["ratio"], float)

        self.assertEqual(result["negative"], -5)

        self.assertEqual(result["zero"], 0)

    def test_malformed_yaml_raises_valueerror(self) -> None:
        """We should raise ValueError when YAML is malformed."""
        # Odd number of spaces breaks indentation
        with self.assertRaises(ValueError):
            parse_yaml("  bad_indent: value\n    worse: other")

        # Missing colon means broken syntax
        with self.assertRaises(ValueError):
            parse_yaml("no_colon_here")

    def test_parse_quoted_strings_preserve_content(self) -> None:
        """Strip quotes but preserve the actual content inside."""
        yaml_text = '''name: "hello world"
port_str: "22"
bool_str: "true"
empty: ""'''
        result = parse_yaml(yaml_text)

        # We remove the quotes but keep what's inside
        self.assertEqual(result["name"], "hello world")

        # When quoted, "22" stays a string, doesn't become an int
        self.assertEqual(result["port_str"], "22")

        # Same deal "true" as a quoted string stays a string
        self.assertEqual(result["bool_str"], "true")

        # Empty quoted string gives us an empty string, not None
        self.assertEqual(result["empty"], "")


if __name__ == '__main__':
    unittest.main()
