"""Tests for network targets: port reachability, SFTd health, TURN connectivity, and firewall rules.

Most of these are straightforward network checks; _count_rules is just a utility
for parsing different firewall config formats.
"""

from __future__ import annotations

from typing import Any
from unittest.mock import patch

from src.lib.command import CommandResult
from src.lib.http_client import HttpResult
from src.lib.logger import Logger, LogLevel
from src.lib.terminal import Terminal, Verbosity
from src.test.conftest import make_minimal_config
from src.targets.network.port_reachability import PortReachability
from src.targets.network.sftd_reachable import SftdReachable
from src.targets.network.turn_connectivity import TurnConnectivity
from src.targets.network.firewall_rules import _count_rules


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_terminal() -> Terminal:
    """Quiet terminal for tests; no noise in output."""
    return Terminal(verbosity=Verbosity.QUIET, use_color=False)


def _make_logger() -> Logger:
    """Logger that only shows errors; quiet for tests."""
    return Logger(level=LogLevel.ERROR)


def _ssh_cmd_result(stdout: str) -> CommandResult:
    """Successful SSH command result with given output."""
    return CommandResult(
        command="ssh test",
        exit_code=0,
        stdout=stdout,
        stderr="",
        duration_seconds=0.1,
        success=True,
        timed_out=False,
    )


def _kubectl_cmd_result(stdout: str = "{}") -> CommandResult:
    """Successful kubectl command result with given JSON output."""
    return CommandResult(
        command="kubectl get",
        exit_code=0,
        stdout=stdout,
        stderr="",
        duration_seconds=0.1,
        success=True,
        timed_out=False,
    )


# ---------------------------------------------------------------------------
# _count_rules helper
# ---------------------------------------------------------------------------

def test_count_rules_iptables() -> None:
    """Iptables format uses «-A» lines for rules; should count all three."""
    output: str = (
        "# Generated by iptables-save\n"
        "*filter\n"
        ":INPUT ACCEPT [0:0]\n"
        "-A INPUT -p tcp --dport 22 -j ACCEPT\n"
        "-A INPUT -p tcp --dport 443 -j ACCEPT\n"
        "-A FORWARD -j DROP\n"
        "COMMIT\n"
    )
    assert _count_rules("iptables", output) == 3


def test_count_rules_nftables() -> None:
    """Nftables counts «accept» and «drop» keywords; we get 3 total."""
    output: str = (
        "table inet filter {\n"
        "  chain input {\n"
        "    type filter hook input priority 0;\n"
        "    ct state established,related accept\n"
        "    tcp dport 22 accept\n"
        "    drop\n"
        "  }\n"
        "}\n"
    )
    assert _count_rules("nftables", output) == 3


def test_count_rules_ufw() -> None:
    """Ufw format has two actual rules after the header row."""
    output: str = (
        "Status: active\n"
        "To                         Action      From\n"
        "--                         ------      ----\n"
        "22/tcp                     ALLOW       Anywhere\n"
        "443/tcp                    ALLOW       Anywhere\n"
    )
    assert _count_rules("ufw", output) == 2


def test_count_rules_empty() -> None:
    """Empty output means zero rules, obviously."""
    assert _count_rules("iptables", "") == 0


def test_count_rules_unknown_type() -> None:
    """Unknown firewall type; can't parse so returns 0."""
    assert _count_rules("unknown", "some output") == 0


# ---------------------------------------------------------------------------
# PortReachability
# ---------------------------------------------------------------------------

def test_port_reachability_description() -> None:
    """Should mention 443 in the description."""
    target: PortReachability = PortReachability(make_minimal_config(), _make_terminal(), _make_logger())
    assert "443" in target.description


def test_port_reachability_all_open() -> None:
    """All three ports open; should report 3/3."""
    target: PortReachability = PortReachability(make_minimal_config(), _make_terminal(), _make_logger())

    with patch("src.lib.ssh.SSHTarget.run", return_value=_ssh_cmd_result("OPEN\n")):
        result: str = target.collect()

    assert "3/3" in result


def test_port_reachability_some_closed() -> None:
    """One port open, two closed; should report 1/3."""
    call_count: int = 0

    def _alternating(*args: object, **kwargs: object) -> CommandResult:
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            return _ssh_cmd_result("OPEN\n")
        return _ssh_cmd_result("CLOSED\n")

    target: PortReachability = PortReachability(make_minimal_config(), _make_terminal(), _make_logger())

    with patch("src.lib.ssh.SSHTarget.run", side_effect=_alternating):
        result: str = target.collect()

    assert "1/3" in result


# ---------------------------------------------------------------------------
# SftdReachable
# ---------------------------------------------------------------------------

def test_sftd_reachable_description() -> None:
    """Should mention SFTd in the description."""
    target: SftdReachable = SftdReachable(make_minimal_config(), _make_terminal(), _make_logger())
    assert "sftd" in target.description.lower()


def _http_result(status_code: int, error: str | None = None) -> HttpResult:
    """Fake HTTP response with given status code."""
    return HttpResult(
        url="https://sftd.example.com/",
        status_code=status_code,
        body="",
        headers={},
        duration_seconds=0.1,
        success=200 <= status_code < 400,
        error=error,
    )


def test_sftd_reachable_responds() -> None:
    """HTTP 200; SFTd is responsive."""
    target: SftdReachable = SftdReachable(make_minimal_config(), _make_terminal(), _make_logger())

    with patch("src.lib.base_target.http_get", return_value=_http_result(200)):
        result: bool = target.collect()

    assert result is True


def test_sftd_reachable_404_still_true() -> None:
    """404 still means the server's up and responding."""
    target: SftdReachable = SftdReachable(make_minimal_config(), _make_terminal(), _make_logger())

    with patch("src.lib.base_target.http_get", return_value=_http_result(404)):
        result: bool = target.collect()

    assert result is True


def test_sftd_reachable_500_returns_false() -> None:
    """500 error means something's broken; should fail."""
    target: SftdReachable = SftdReachable(make_minimal_config(), _make_terminal(), _make_logger())

    with patch("src.lib.base_target.http_get", return_value=_http_result(500)):
        result: bool = target.collect()

    assert result is False


def test_sftd_reachable_no_response() -> None:
    """Can't reach the server at all; connection refused."""
    target: SftdReachable = SftdReachable(make_minimal_config(), _make_terminal(), _make_logger())

    with patch("src.lib.base_target.http_get", return_value=_http_result(0, error="Connection refused")):
        result: bool = target.collect()

    assert result is False


# ---------------------------------------------------------------------------
# TurnConnectivity
# ---------------------------------------------------------------------------

def test_turn_connectivity_description() -> None:
    """Should mention TURN protocol."""
    target: TurnConnectivity = TurnConnectivity(make_minimal_config(), _make_terminal(), _make_logger())
    assert "TURN" in target.description


def test_turn_connectivity_all_signals() -> None:
    """UDP works, TCP works, coturn pod is running; everything checks out."""
    pods_data: dict[str, Any] = {"items": [
        {"status": {"phase": "Running"}},
    ]}
    target: TurnConnectivity = TurnConnectivity(make_minimal_config(), _make_terminal(), _make_logger())

    with patch("src.lib.base_target.run_command", side_effect=[
        _ssh_cmd_result("EXIT:0"),
        _ssh_cmd_result("OPEN"),
    ]):
        with patch("src.lib.base_target.kubectl_get", return_value=(_kubectl_cmd_result(), pods_data)):
            result: bool = target.collect()

    assert result is True


def test_turn_connectivity_no_signals() -> None:
    """UDP down, TCP down, no pods running; everything fails."""
    pods_data: dict[str, Any] = {"items": []}
    target: TurnConnectivity = TurnConnectivity(make_minimal_config(), _make_terminal(), _make_logger())

    with patch("src.lib.base_target.run_command", side_effect=[
        _ssh_cmd_result("EXIT:1"),
        _ssh_cmd_result("CLOSED"),
    ]):
        with patch("src.lib.base_target.kubectl_get", return_value=(_kubectl_cmd_result(), pods_data)):
            result: bool = target.collect()

    assert result is False
