/**
 * Wire settings YAML generator pure transformation utility that takes SetupData
 * and returns a wire-facts-settings.yaml string. No Vue or reactive dependencies
 * here, just extracted from App.vue so we can test it without a Vue harness.
 *
 * yaml_node_list: formats an IP array as indented YAML list lines
 * generate_settings_yaml: builds the full settings YAML string from form data
 */

// Types
export interface SetupData {
    admin_host_ip:      string
    admin_user:         string
    cluster_domain:     string
    k8s_namespace:      string
    cassandra_host:     string
    elasticsearch_host: string
    minio_host:         string
    postgres_host:      string
    rabbitmq_host:      string
    ssh_key_path:       string
    ssh_port:           string
    db_ssh_user:        string
    db_ssh_key:         string
    kube_nodes:         string[]
    data_nodes:         string[]
    // Deployment feature flags tell the checkers what to expect so they
    // don't warn about features that aren't part of this deployment
    expect_metrics:             boolean
    expect_sso:                 boolean
    expect_deeplink:            boolean
    expect_sms:                 boolean
    expect_sft:                 boolean
    using_ephemeral_databases:  boolean
    // Site-survey-derived flags (infrastructure)
    wire_managed_cluster:       boolean
    has_internet:               boolean
    has_dns:                    boolean
    users_access_externally:    boolean
    // Calling
    expect_calling:             boolean
    calling_type:               string     // "on_prem" | "cloud"
    calling_in_dmz:             boolean
    // Federation
    expect_federation:          boolean
    federation_domains:         string[]
    // Features
    expect_legalhold:           boolean
    // Kubeconfig paths (used in Step 4 commands, not written to YAML)
    kubeconfig_path:            string
    calling_kubeconfig_path:    string
}

// Escape backslashes then double-quotes so values are safe inside YAML double-quoted scalars.
// Backslashes must be escaped first, otherwise the backslash added by the quote-escape pass
// becomes a YAML escape sequence itself (like \U, \n) and breaks the scalar.
function yaml_esc(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

// Build YAML list lines for a node IP array each IP gets its own indented line
function yaml_node_list(ips: string[], indent: string = '  '): string {
    if (ips.length === 0) return `${indent}[]`
    return ips.map((ip) => `${indent}- "${yaml_esc(ip)}"`).join('\n')
}

// Build YAML list lines for domain strings
function yaml_string_list(items: string[], indent: string = '  '): string {
    if (items.length === 0) return `${indent}[]`
    return items.map((item) => `${indent}- "${yaml_esc(item)}"`).join('\n')
}

// Generate YAML settings file from form data
export function generate_settings_yaml(s: SetupData): string {
    // Only include nodes section if there's actually something to list
    const has_nodes = s.kube_nodes.length > 0 || s.data_nodes.length > 0
    const nodes_section = has_nodes ? `

# Explicit VM node lists (override dynamic host discovery when non-empty)
nodes:
  kube_nodes:
${yaml_node_list(s.kube_nodes, '    ')}
  data_nodes:
${yaml_node_list(s.data_nodes, '    ')}` : ''

    return `# Wire Fact Gathering Tool - Settings File
# Generated by Wire Fact Gathering Tool
# Save this file as wire-facts-settings.yaml on your admin host

# Connection settings for the admin host
admin_host:
  ip: "${yaml_esc(s.admin_host_ip || '10.0.0.1')}"
  user: "${yaml_esc(s.admin_user || 'wire-admin')}"
  ssh_key: "${yaml_esc(s.ssh_key_path || '~/.ssh/wire_deploy')}"
  ssh_port: ${parseInt(s.ssh_port, 10) || 22}

# Wire cluster settings
cluster:
  domain: "${yaml_esc(s.cluster_domain || 'wire.example.com')}"
  kubernetes_namespace: "${yaml_esc(s.k8s_namespace || 'wire')}"

# Database host addresses
databases:
  cassandra: "${yaml_esc(s.cassandra_host || '10.0.0.10')}"
  elasticsearch: "${yaml_esc(s.elasticsearch_host || '10.0.0.11')}"
  minio: "${yaml_esc(s.minio_host || '10.0.0.12')}"
  postgresql: "${yaml_esc(s.postgres_host || '10.0.0.13')}"
  rabbitmq: "${yaml_esc(s.rabbitmq_host || '10.0.0.14')}"${s.db_ssh_key ? `
  # SSH credentials for reaching database VMs via the admin host (jump host)
  ssh_user: "${yaml_esc(s.db_ssh_user)}"
  ssh_key: "${yaml_esc(s.db_ssh_key)}"` : ''}${nodes_section}

# Fact gathering options
options:
  # Check all components by default
  check_kubernetes: true
  check_databases: true
  check_network: true
  check_wire_services: true
  # Output format
  output_format: "jsonl"
  output_file: "wire-facts-results.jsonl"
  # Deployment feature flags - checkers skip warnings for features not in use
  expect_metrics: ${s.expect_metrics}
  expect_sso: ${s.expect_sso}
  expect_deeplink: ${s.expect_deeplink}
  expect_sms: ${s.expect_sms}
  expect_sft: ${s.expect_sft}
  using_ephemeral_databases: ${s.using_ephemeral_databases}
  # Site-survey-derived flags
  wire_managed_cluster: ${s.wire_managed_cluster}
  has_internet: ${s.has_internet}
  has_dns: ${s.has_dns}
  users_access_externally: ${s.users_access_externally}
  expect_calling: ${s.expect_calling}
  calling_type: "${yaml_esc(s.calling_type)}"
  calling_in_dmz: ${s.calling_in_dmz}
  expect_federation: ${s.expect_federation}
  federation_domains:
${yaml_string_list(s.federation_domains, '    ')}
  expect_legalhold: ${s.expect_legalhold}`
}
