#!/usr/bin/env python3
"""Entry point for the Wire Fact Gathering Tool runner.

Collects data about a Wire backend install and outputs JSONL for the UI.

Usage:
    # Run on the admin host (default, recommended)
    python3 src/script/runner.py --source admin-host --config config.yaml --output results.jsonl

    # Run from a remote machine via SSH into the admin host
    python3 src/script/runner.py --source ssh-into-admin-host --config config.yaml --output results.jsonl

    # Run in client mode (test reachability from a client network)
    python3 src/script/runner.py --source client --network-name office-lan --config config.yaml --output results.jsonl

    # Run against a specific cluster with explicit kubeconfig
    python3 src/script/runner.py --source admin-host --kubeconfig /path/to/kubeconfig --config config.yaml --output results.jsonl

    # Run only main-cluster targets (skip calling-cluster targets)
    python3 src/script/runner.py --source admin-host --cluster-type main --config config.yaml --output results.jsonl

    # Preflight checks only
    python3 src/script/runner.py --config config.yaml --only-preflight-checks

Exit codes:
    0: success (targets collected, or preflight passed)
    1: one or more targets failed
    2: config file broken or invalid
    3: preflight checks failed
"""

from __future__ import annotations

# External
import argparse
import os
import sys

# Resolve the project root so this script can be run from any working directory
# without requiring the caller to have set PYTHONPATH beforehand.
script_dir: str = os.path.dirname(os.path.abspath(__file__))
project_root: str = os.path.dirname(os.path.dirname(script_dir))
sys.path.insert(0, project_root)

# Ours
from src.lib.runner import Runner
from src.lib.terminal import Verbosity


def main() -> int:
    """Parse args and run the gatherer.

    Args:
        (none, reads from sys.argv via argparse)

    Returns:
        Exit code (0 = success, 1 = target failures, 2 = config error).
    """
    # RawDescriptionHelpFormatter keeps the docstring's multi-line examples intact
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description="Wire Fact Gathering Tool - collects infrastructure health data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # Config file is mandatory, has all SSH/DB/cluster stuff
    parser.add_argument(
        "--config",
        required=True,
        help="Path to the YAML config file (generated by the UI)",
    )

    # Output path required unless --only-preflight-checks is set
    parser.add_argument(
        "--output",
        default="",
        help="Path to output JSONL file. Required unless --only-preflight-checks.",
    )

    # Target filter, defaults to '*' (all targets)
    parser.add_argument(
        "--target",
        default="*",
        help="Target filter. Examples: '*', 'databases/cassandra/*', 'kubernetes'. Default: '*'",
    )

    # Verbose: show full command output
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show full command output including stdout/stderr",
    )

    # Quiet: suppress per-target output
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Show summary only, suppress per-target output",
    )

    # No-color: safe for log files
    parser.add_argument(
        "--no-color",
        action="store_true",
        help="Disable ANSI color codes in output",
    )

    # Source: where the gatherer is running from
    parser.add_argument(
        "--source",
        choices=["admin-host", "ssh-into-admin-host", "client"],
        default="admin-host",
        help=(
            "Where the gatherer runs: "
            "'admin-host' (default, directly on the Wire deploy host), "
            "'ssh-into-admin-host' (SSH from a remote machine into the admin host), or "
            "'client' (client-side probe mode — no SSH/kubectl, tests external reachability only)."
        ),
    )

    # Network name: human-readable label for this run
    parser.add_argument(
        "--network-name",
        default="",
        help=(
            "Human-readable label for this runner invocation. "
            "Stored in the output file and shown in the report UI. "
            "Examples: 'main-cluster', 'calling-dmz', 'office-lan', 'home-vpn'."
        ),
    )

    # Kubeconfig: explicit path to kubeconfig file
    parser.add_argument(
        "--kubeconfig",
        default="",
        help=(
            "Path to kubeconfig file. Sets KUBECONFIG env var for kubectl commands. "
            "When not specified, uses the default kubectl context. "
            "Ignored in --source client mode."
        ),
    )

    # Cluster type: which cluster's targets to run
    parser.add_argument(
        "--cluster-type",
        choices=["both", "main", "calling"],
        default="both",
        help=(
            "Which cluster this run targets: "
            "'both' (default, all targets), "
            "'main' (Wire backend only, skip calling targets), or "
            "'calling' (calling cluster only, skip main-cluster targets). "
            "Ignored in --source client mode."
        ),
    )

    # Parallel: number of concurrent targets
    parser.add_argument(
        "--parallel",
        type=int,
        default=1,
        metavar="N",
        help="Run N targets concurrently. Default: 1 (sequential).",
    )

    # Preflight-only: run connectivity checks and exit
    parser.add_argument(
        "--only-preflight-checks",
        action="store_true",
        help=(
            "Run preflight checks (SSH, kubectl) and exit. "
            "Exit 0 = all passed, 3 = some failed. "
            "Doesn't require --output."
        ),
    )

    # Force: skip preflight checks
    parser.add_argument(
        "--force-no-preflight-checks",
        action="store_true",
        help=(
            "Skip all preflight checks and collect data immediately. "
            "Use when config is known-good or a check is incorrectly blocking."
        ),
    )

    # K8s-only mode: skip targets that need SSH
    parser.add_argument(
        "--only-through-kubernetes",
        action="store_true",
        help=(
            "Only run targets that use kubectl. Skip all targets that need "
            "SSH access to VMs, database hosts, or the admin host. Use this "
            "for deployments where only Kubernetes access is available."
        ),
    )

    # Dry-run mode: show what commands would be executed without running them
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Show what commands would be executed without actually running them. "
            "Prints a table of all commands, their execution paths (SSH hops, "
            "docker wrapping, etc.), and which target triggers each one. "
            "No output file is produced and no connections are made."
        ),
    )

    args: argparse.Namespace = parser.parse_args()

    # --output not required for preflight-only or dry-run modes
    if not args.only_preflight_checks and not args.dry_run and not args.output:
        parser.error("--output required (not needed with --only-preflight-checks or --dry-run)")

    # Client mode + preflight-only doesn't make sense (no SSH/kubectl to check)
    if args.source == 'client' and args.only_preflight_checks:
        parser.error("--only-preflight-checks is not supported in client mode (no SSH/kubectl)")

    # Set KUBECONFIG env var if explicitly provided (before Runner instantiation)
    if args.kubeconfig:
        kubeconfig_path: str = os.path.expanduser(args.kubeconfig)
        if not os.path.exists(kubeconfig_path):
            print(f"Error: kubeconfig file not found: {kubeconfig_path}", file=sys.stderr)
            return 2
        os.environ['KUBECONFIG'] = kubeconfig_path

    # Quiet wins if both are set
    if args.quiet:
        verbosity: Verbosity = Verbosity.QUIET
    elif args.verbose:
        verbosity = Verbosity.VERBOSE
    else:
        verbosity = Verbosity.NORMAL

    parallel: int = max(1, args.parallel)

    # Map the --source value to gathered_from for backward compatibility.
    # The old name «external» is now «ssh-into-admin-host» in the CLI but
    # internally we keep the mapping consistent.
    gathered_from: str = args.source

    # Derive source_type from gathered_from
    source_type: str = 'client' if gathered_from == 'client' else 'backend'

    runner: Runner = Runner(
        config_path             = args.config,
        output_path             = args.output,
        target_pattern          = args.target,
        verbosity               = verbosity,
        use_color               = not args.no_color,
        gathered_from           = gathered_from,
        only_through_kubernetes = args.only_through_kubernetes,
        parallel                = parallel,
        only_preflight          = args.only_preflight_checks,
        force_no_preflight      = args.force_no_preflight_checks,
        network_name            = args.network_name,
        source_type             = source_type,
        cluster_type            = args.cluster_type,
        kubeconfig_path         = args.kubeconfig,
        dry_run                 = args.dry_run,
    )

    return runner.run()


if __name__ == "__main__":
    sys.exit(main())
